# Generated by Django 4.0.2 on 2022-02-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('kingdom', models.CharField(max_length=60)),
                ('phylum', models.CharField(max_length=60)),
                ('classname', models.CharField(max_length=60)),
                ('order', models.CharField(max_length=60)),
                ('family', models.CharField(max_length=60)),
                ('genus', models.CharField(max_length=60)),
                ('scientificname', models.CharField(max_length=150)),
            ],
        ),
    ]
