# Generated by Django 4.0.2 on 2022-03-22 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_animal_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='image',
        ),
    ]
